<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SharedWorlds.GameAdapters.ConanExilesEnhanced</AssemblyName>
    <RootNamespace>SharedWorlds.GameAdapters.ConanExilesEnhanced</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../SharedWorlds.Core/SharedWorlds.Core.csproj" />
  </ItemGroup>
</Project>
