[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$ClientAppDirectory,
    [Parameter(Mandatory = $true)]
    [string]$BackendInputDirectory,
    [string]$Version = '2.0.0-beta.1',
    [string]$OutputDirectory
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Fail([string]$Message) {
    Write-Error $Message
    exit 1
}

$repoRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$clientSource = [IO.Path]::GetFullPath($ClientAppDirectory)
$backendSource = [IO.Path]::GetFullPath($BackendInputDirectory)
if ($Version -notmatch '^[0-9A-Za-z][0-9A-Za-z.-]{0,63}$') { Fail 'Version is malformed.' }
if (-not [IO.Directory]::Exists($clientSource)) { Fail "Client app directory not found: $clientSource" }
if (-not [IO.Directory]::Exists($backendSource)) { Fail "Backend input directory not found: $backendSource" }

$requiredClient = @('SharedWorlds.Desktop.exe', 'SharedWorlds.Desktop.dll', 'acceptance-build.json')
foreach ($file in $requiredClient) {
    if (-not [IO.File]::Exists((Join-Path $clientSource $file))) { Fail "Client app is incomplete: $file" }
}
if ([IO.File]::Exists((Join-Path $clientSource 'steward-friends-build.json')) -or
    [IO.File]::Exists((Join-Path $clientSource 'steward-steam-release.json'))) {
    Fail 'Closed-beta client input must not contain a build-time remote endpoint configuration.'
}

$backendTar = @(Get-ChildItem -LiteralPath $backendSource -File -Filter '*.tar')
$backendMetadata = Join-Path $backendSource 'backend-metadata.json'
if ($backendTar.Count -ne 1 -or -not [IO.File]::Exists($backendMetadata)) {
    Fail 'Backend input must contain exactly one image TAR and backend-metadata.json.'
}

if ([string]::IsNullOrWhiteSpace($OutputDirectory)) {
    $OutputDirectory = Join-Path $repoRoot 'artifacts/closed-beta'
}
$output = [IO.Path]::GetFullPath($OutputDirectory)
[IO.Directory]::CreateDirectory($output) | Out-Null
$rootName = "Steward-$Version-ClosedBeta"
$stage = Join-Path $output $rootName
$zipPath = Join-Path $output "$rootName.zip"
$shaPath = "$zipPath.sha256"
foreach ($path in @($stage, $zipPath, $shaPath)) {
    if ([IO.Directory]::Exists($path)) { Remove-Item -LiteralPath $path -Recurse -Force }
    if ([IO.File]::Exists($path)) { Remove-Item -LiteralPath $path -Force }
}

$clientTarget = Join-Path $stage 'client'
$clientAppTarget = Join-Path $clientTarget 'app'
$serverTarget = Join-Path $stage 'server'
$serverBackendTarget = Join-Path $serverTarget 'backend'
[IO.Directory]::CreateDirectory($clientAppTarget) | Out-Null
[IO.Directory]::CreateDirectory($serverBackendTarget) | Out-Null

Copy-Item -LiteralPath (Join-Path $repoRoot 'beta/client/Start-Steward.ps1') -Destination $clientTarget
Copy-Item -LiteralPath (Join-Path $repoRoot 'beta/client/Start-Steward.cmd') -Destination $clientTarget
Copy-Item -LiteralPath (Join-Path $repoRoot 'beta/client/steward-beta.json.example') -Destination $clientTarget
Copy-Item -Path (Join-Path $clientSource '*') -Destination $clientAppTarget -Recurse
Copy-Item -LiteralPath (Join-Path $repoRoot 'beta/server/docker-compose.yml') -Destination $serverTarget
Copy-Item -LiteralPath (Join-Path $repoRoot 'beta/server/Caddyfile') -Destination $serverTarget
Copy-Item -LiteralPath (Join-Path $repoRoot 'beta/server/Install-Steward-Beta.ps1') -Destination $serverTarget
Copy-Item -LiteralPath (Join-Path $repoRoot 'beta/server/Stop-Steward-Beta.ps1') -Destination $serverTarget
Copy-Item -LiteralPath $backendTar[0].FullName -Destination (Join-Path $serverBackendTarget 'steward-backend.tar')
Copy-Item -LiteralPath $backendMetadata -Destination $serverBackendTarget

$readme = @"
STEWARD CLOSED BETA $Version
============================

This is the runnable closed-beta product bundle, not an acceptance/test harness.

SERVER REQUIREMENTS
- PowerShell 7 (`pwsh`).
- Docker with Docker Compose v2 and Linux/amd64 container support.
- A machine reachable from the Internet on TCP 80 and 443.
- A public DNS A record such as beta.example.com pointing to that machine.

SERVER INSTALL
From the server directory run:

  pwsh ./Install-Steward-Beta.ps1 `
    -Domain beta.example.com `
    -OwnerDisplayName "Owner" `
    -FriendDisplayName "Friend"

The installer:
- pulls digest-pinned PostgreSQL 17, MinIO and Caddy images;
- loads the exact Steward backend image included here;
- creates durable PostgreSQL/object-store/Caddy volumes;
- generates backend secrets and two independent tester credentials;
- exposes only Caddy on ports 80/443;
- waits for https://<domain>/health/ready;
- writes output/Steward-ClosedBeta-Client.zip for distribution.

CLIENT
Give each tester the SAME configured client ZIP generated by the server installer.
Give each tester only their own credential from server/output/credentials/.
Extract the client ZIP and double-click Start-Steward.cmd.
When Steward asks for the private Friends Build code, paste that tester's own credential.

DATA
Do not delete Docker volumes unless you intentionally want to destroy beta data.
server/Stop-Steward-Beta.ps1 stops the stack without deleting data by default.

SECURITY
The distribution ZIP contains no database password, object-store password, tester credential,
TLS private key, or backend secret. Those are generated at installation time and remain on the server.
"@
[IO.File]::WriteAllText((Join-Path $stage 'README.txt'), $readme, [Text.UTF8Encoding]::new($false))

$commit = (& git -C $repoRoot rev-parse HEAD 2>$null).Trim()
$files = @(Get-ChildItem -LiteralPath $stage -Recurse -File | Sort-Object FullName | ForEach-Object {
    [ordered]@{
        path = [IO.Path]::GetRelativePath($stage, $_.FullName).Replace('\\', '/')
        byteSize = [int64]$_.Length
        sha256 = (Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash.ToUpperInvariant()
    }
})
$manifest = [ordered]@{
    documentType = 'steward.closed-beta-product'
    schemaVersion = 1
    version = $Version
    commitSha = $commit
    builtAtUtc = [DateTimeOffset]::UtcNow.ToString('O')
    clientConfiguration = 'deploy-time'
    authenticationMode = 'friends-build'
    serverStack = @('Backend.Api', 'PostgreSQL 17', 'S3-compatible MinIO', 'Caddy HTTPS')
    containsSecrets = $false
    files = $files
}
[IO.File]::WriteAllText(
    (Join-Path $stage 'beta-manifest.json'),
    ($manifest | ConvertTo-Json -Depth 6),
    [Text.UTF8Encoding]::new($false))

Compress-Archive -LiteralPath $stage -DestinationPath $zipPath -CompressionLevel Optimal
$hash = (Get-FileHash -LiteralPath $zipPath -Algorithm SHA256).Hash.ToUpperInvariant()
[IO.File]::WriteAllText($shaPath, "$hash  $([IO.Path]::GetFileName($zipPath))`n", [Text.UTF8Encoding]::new($false))

Write-Host
Write-Host '[OK] Steward closed-beta product bundle built.'
Write-Host "  ZIP: $zipPath"
Write-Host "  SHA-256: $hash"
Write-Host "  Files: $($files.Count + 1)"
Write-Host '  Secrets embedded: no'
