[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$BundleDirectory,
    [Parameter(Mandatory=$true)][string]$RequestPath,
    [Parameter(Mandatory=$true)][string]$DeploymentEvidenceDirectory,
    [Parameter(Mandatory=$true)][string]$ExternalIngressAcceptanceEvidencePath,
    [Parameter(Mandatory=$true)][string]$EvidencePath
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
function Require([bool]$Condition,[string]$Message){if(-not $Condition){throw $Message}}
function Artifact([object[]]$Items,[string]$Name){$m=@($Items|Where-Object{[string]$_.path -ceq $Name});Require($m.Count -eq 1) "Artifact '$Name' must appear exactly once.";return $m[0]}
function Bound([string]$Root,[object[]]$Items,[string]$Name){$p=[IO.Path]::GetFullPath((Join-Path $Root $Name));Require([IO.File]::Exists($p)) "Missing bundled file: $Name";$i=Get-Item -LiteralPath $p;Require($null -eq $i.LinkType -and $i.Length -gt 0 -and $i.Length -le 2MB) "Invalid bundled file: $Name";$a=Artifact $Items $Name;$h=(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToUpperInvariant();Require($i.Length -eq [int64]$a.byteSize -and $h -ceq [string]$a.sha256) "Bundled file does not match manifest: $Name";return $p}
function ReadEvidence([string]$Path,[string]$Type,[string]$Version,[string]$Commit,[string]$RequestHash){$p=[IO.Path]::GetFullPath($Path);Require([IO.File]::Exists($p)) "Missing evidence: $p";$i=Get-Item -LiteralPath $p;Require($null -eq $i.LinkType -and $i.Length -gt 0 -and $i.Length -le 1MB) "Invalid evidence: $p";$j=[IO.File]::ReadAllText($p)|ConvertFrom-Json;Require([string]$j.documentType -ceq $Type -and [int]$j.schemaVersion -eq 1) "Wrong evidence identity: $Type";Require([string]$j.releaseVersion -ceq $Version -and [string]$j.releaseCommitSha -ceq $Commit -and [string]$j.requestSha256 -ceq $RequestHash) "Evidence binding mismatch: $Type";Require(-not [bool]$j.publishAllowed -and [string]$j.physicalBringHere -ceq 'deferred' -and -not [bool]$j.publicationAuthorizationChanged) "Evidence changed publication state: $Type";return [ordered]@{Path=$p;File=[IO.Path]::GetFileName($p);Json=$j;Size=$i.Length;Hash=(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToUpperInvariant();Type=$Type}}
$root=[IO.Path]::GetFullPath($BundleDirectory);Require([IO.Directory]::Exists($root)) 'Bundle directory is missing.'
$manifestPath=Join-Path $root 'release-manifest.json';Require([IO.File]::Exists($manifestPath)) 'Release manifest is missing.'
$manifest=[IO.File]::ReadAllText($manifestPath)|ConvertFrom-Json;Require([string]$manifest.documentType -ceq 'steward.closed-alpha-release-candidate' -and [int]$manifest.schemaVersion -eq 1 -and [string]$manifest.channel -ceq 'closed-alpha') 'Release manifest identity is invalid.';Require(-not [bool]$manifest.publishAuthorization.publishAllowed -and [string]$manifest.publishAuthorization.physicalBringHere -ceq 'deferred') 'Execution finalization requires deferred publication.'
$items=@($manifest.artifacts);$verifier=Bound $root $items 'verify-closed-alpha-release.ps1';$self=Bound $root $items 'finalize-closed-alpha-live-host-execution.ps1';Require([string]::Equals([IO.Path]::GetFullPath($PSCommandPath),$self,[StringComparison]::OrdinalIgnoreCase)) 'Run finalization from inside the release bundle.';& $verifier -BundleDirectory $root
$version=[string]$manifest.version;$commit=[string]$manifest.commitSha
$request=[IO.Path]::GetFullPath($RequestPath);Require([IO.File]::Exists($request)) 'Request is missing.';$ri=Get-Item -LiteralPath $request;Require($null -eq $ri.LinkType -and $ri.Length -gt 0 -and $ri.Length -le 1MB) 'Request is invalid.';$requestHash=(Get-FileHash -LiteralPath $request -Algorithm SHA256).Hash.ToUpperInvariant()
$dir=[IO.Path]::GetFullPath($DeploymentEvidenceDirectory);Require([IO.Directory]::Exists($dir)) 'Deployment evidence directory is missing.';$expected=@('01-live-host-preflight.json','02-live-plan-staging.json','03-live-backend-deployment.json','04-live-ingress-activation.json','deployment-handoff.json')|Sort-Object;$actual=@(Get-ChildItem -LiteralPath $dir -File -Force|ForEach-Object{$_.Name}|Sort-Object);Require($actual.Count -eq $expected.Count -and @(Compare-Object $actual $expected).Count -eq 0) 'Deployment evidence directory contains missing or unexpected files.'
$p=ReadEvidence (Join-Path $dir '01-live-host-preflight.json') 'steward.closed-alpha-live-host-preflight' $version $commit $requestHash
$s=ReadEvidence (Join-Path $dir '02-live-plan-staging.json') 'steward.closed-alpha-live-plan-staging' $version $commit $requestHash
$b=ReadEvidence (Join-Path $dir '03-live-backend-deployment.json') 'steward.closed-alpha-live-backend-deployment' $version $commit $requestHash
$i=ReadEvidence (Join-Path $dir '04-live-ingress-activation.json') 'steward.closed-alpha-live-ingress-activation' $version $commit $requestHash
$h=ReadEvidence (Join-Path $dir 'deployment-handoff.json') 'steward.closed-alpha-live-host-deployment-handoff' $version $commit $requestHash
$x=ReadEvidence $ExternalIngressAcceptanceEvidencePath 'steward.closed-alpha-external-ingress-acceptance' $version $commit $requestHash
Require([string]$s.Json.preflightEvidenceSha256 -ceq $p.Hash) 'Staging does not bind exact preflight evidence.';Require([string]$b.Json.stagingEvidenceSha256 -ceq $s.Hash) 'Backend does not bind exact staging evidence.';Require([string]$i.Json.backendDeploymentEvidenceSha256 -ceq $b.Hash) 'Ingress does not bind exact backend evidence.';Require([string]$x.Json.ingressActivationEvidenceSha256 -ceq $i.Hash) 'External acceptance does not bind exact ingress evidence.'
Require([int]$h.Json.deploymentStageCount -eq 4 -and [bool]$h.Json.allDeploymentStagesSucceeded -and -not [bool]$h.Json.externalAcceptancePerformed -and [bool]$h.Json.externalAcceptanceRequiresSeparateObserver) 'Deployment handoff is incomplete.';Require(-not [bool]$x.Json.observerUsedSsh -and -not [bool]$x.Json.hostMutationPerformed -and -not [bool]$x.Json.protectedEnvironmentAccessed) 'External observation crossed its read-only boundary.';Require([bool]$x.Json.publicHttpsVerified -and [bool]$x.Json.externalPort8080ClosedVerified -and [string]$x.Json.certificateValidationMode -ceq 'system-trust-default-no-bypass' -and [int]$x.Json.tlsVerifyResult -eq 0) 'External acceptance is incomplete.'
$handoffStages=@($h.Json.stageEvidence);Require($handoffStages.Count -eq 4) 'Deployment handoff has the wrong stage count.';$hashes=@($p.Hash,$s.Hash,$b.Hash,$i.Hash);for($n=0;$n -lt 4;$n++){Require([string]$handoffStages[$n].sha256 -ceq [string]$hashes[$n]) "Deployment handoff stage hash mismatch at index $n."}
$out=[IO.Path]::GetFullPath($EvidencePath);Require(-not [IO.File]::Exists($out)) 'Final chain evidence already exists.';$od=[IO.Path]::GetDirectoryName($out);[IO.Directory]::CreateDirectory($od)|Out-Null
$stages=@($p,$s,$b,$i,$x|ForEach-Object{[ordered]@{file=$_.File;documentType=$_.Type;byteSize=$_.Size;sha256=$_.Hash}})
$chain=[ordered]@{documentType='steward.closed-alpha-live-host-execution-chain';schemaVersion=1;completedAtUtc=[DateTimeOffset]::UtcNow.ToString('O');releaseVersion=$version;releaseCommitSha=$commit;requestSha256=$requestHash;deploymentHandoffSha256=$h.Hash;stageEvidence=$stages;stageCount=5;allStagesSucceeded=$true;deploymentStagesUsedSsh=$true;externalAcceptanceUsedSsh=$false;externalAcceptanceHostMutation=$false;externalObserverSeparation='operator-required-not-machine-attested';automaticCrossStageRollback=$false;publishAllowed=$false;physicalBringHere='deferred';publicationAuthorizationChanged=$false}
$text=$chain|ConvertTo-Json -Depth 7;Require($text.Length -gt 0 -and $text.Length -le 128KB) 'Final chain evidence is invalid.';[IO.File]::WriteAllText($out,$text,[Text.UTF8Encoding]::new($false))
Write-Host '[OK] Deployment evidence and separate external acceptance form one exact chain.';Write-Host '  Deployment: 4/4 stages';Write-Host '  External acceptance: no SSH / no mutation';Write-Host '  Observer separation: operator-required, not machine-attested';Write-Host '  Publication authorization changed: no'
