[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$BundleDirectory,
    [Parameter(Mandatory=$true)][string]$SourceBeforeEvidencePath,
    [Parameter(Mandatory=$true)][string]$TargetAfterEvidencePath,
    [Parameter(Mandatory=$true)][string]$SourceAfterEvidencePath,
    [Parameter(Mandatory=$true)][string]$SourceBeforeScreenshotPath,
    [Parameter(Mandatory=$true)][string]$TargetAvailableScreenshotPath,
    [Parameter(Mandatory=$true)][string]$TargetAfterScreenshotPath,
    [Parameter(Mandatory=$true)][string]$SourceAfterScreenshotPath,
    [Parameter(Mandatory=$true)][string]$LiveHostExecutionChainPath,
    [Parameter(Mandatory=$true)][string]$OutputDirectory
)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'

function Require([bool]$Condition,[string]$Message){if(-not $Condition){throw $Message}}
function ExactProps([object]$Value,[string[]]$Expected,[string]$Context){Require($null -ne $Value) "$Context is null.";$a=@($Value.PSObject.Properties.Name|Sort-Object);$e=@($Expected|Sort-Object);Require($a.Count -eq $e.Count -and @(Compare-Object $a $e).Count -eq 0) "$Context contains missing or unexpected properties."}
function SafeRel([string]$Path){Require(-not [string]::IsNullOrWhiteSpace($Path) -and $Path.Length -le 260) 'Evidence path is missing or too long.';Require(-not [IO.Path]::IsPathRooted($Path) -and -not $Path.Contains('\',[StringComparison]::Ordinal) -and -not $Path.StartsWith('/',[StringComparison]::Ordinal)) "Unsafe evidence path: $Path";foreach($s in @($Path.Split('/'))){Require(-not [string]::IsNullOrEmpty($s) -and $s -cne '.' -and $s -cne '..') "Unsafe evidence path segment: $Path"}}
function ReadJson([string]$Path,[int64]$Max,[string]$Context){$p=[IO.Path]::GetFullPath($Path);Require([IO.File]::Exists($p)) "$Context is missing: $p";$i=Get-Item -LiteralPath $p;Require($null -eq $i.LinkType -and $i.Length -gt 0 -and $i.Length -le $Max) "$Context is invalid or too large.";$t=[IO.File]::ReadAllText($p);return [ordered]@{Path=$p;Item=$i;Text=$t;Json=($t|ConvertFrom-Json);Hash=(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToUpperInvariant()}}
function Canonical([object]$Value){return ($Value|ConvertTo-Json -Compress -Depth 64)}
function RequirePng([string]$Path,[string]$Context){$p=[IO.Path]::GetFullPath($Path);Require([IO.File]::Exists($p)) "$Context is missing.";$i=Get-Item -LiteralPath $p;Require($null -eq $i.LinkType -and $i.Length -ge 100 -and $i.Length -le 20MB) "$Context is invalid or outside the 100-byte..20-MiB bound.";$s=[IO.File]::OpenRead($p);try{$b=[byte[]]::new(8);Require($s.Read($b,0,8) -eq 8) "$Context is truncated.";$sig=[byte[]](0x89,0x50,0x4E,0x47,0x0D,0x0A,0x1A,0x0A);for($n=0;$n -lt 8;$n++){Require($b[$n] -eq $sig[$n]) "$Context is not a PNG screenshot."}}finally{$s.Dispose()};return [ordered]@{Path=$p;Size=$i.Length;Hash=(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToUpperInvariant()}}
function ValidateJournal([object]$Evidence,[string]$Context){$j=$Evidence.journal;$w=$Evidence.world;ExactProps $j @('confirmedEnvironmentRevisionId','confirmedGameAdapterId','confirmedName','confirmedStateRevisionId','desiredEnvironmentRevisionId','desiredGameAdapterId','desiredName','desiredStateRevisionId','installationId','isSynchronized') "$Context journal";Require([bool]$j.isSynchronized) "$Context journal is not synchronized.";Require([string]$j.installationId -ceq [string]$Evidence.installationId) "$Context journal installation mismatch.";Require([string]$j.desiredStateRevisionId -ceq [string]$w.stateRevisionId -and [string]$j.confirmedStateRevisionId -ceq [string]$w.stateRevisionId) "$Context journal state mismatch.";Require([string]$j.desiredEnvironmentRevisionId -ceq [string]$w.environmentRevisionId -and [string]$j.confirmedEnvironmentRevisionId -ceq [string]$w.environmentRevisionId) "$Context journal environment mismatch.";Require([string]$j.desiredName -ceq [string]$w.name -and [string]$j.confirmedName -ceq [string]$w.name) "$Context journal name mismatch.";Require([string]$j.desiredGameAdapterId -ceq [string]$w.gameAdapterId -and [string]$j.confirmedGameAdapterId -ceq [string]$w.gameAdapterId) "$Context journal adapter mismatch."}
function ValidatePhysical([object]$Evidence,[string]$Role,[string]$ReleaseCommit,[string]$Context){ExactProps $Evidence @('build','collectedAtUtc','desktopProcessCount','documentType','installationId','journal','machineName','role','schemaVersion','sourceEvidenceSha256','targetEvidenceSha256','world') $Context;Require([string]$Evidence.documentType -ceq 'safe-world.bring-here-two-pc-evidence' -and [int]$Evidence.schemaVersion -eq 1 -and [string]$Evidence.role -ceq $Role) "$Context identity is invalid.";Require([int]$Evidence.desktopProcessCount -eq 1) "$Context must prove exactly one Safe World Desktop process.";Require(-not [string]::IsNullOrWhiteSpace([string]$Evidence.machineName) -and -not [string]::IsNullOrWhiteSpace([string]$Evidence.installationId)) "$Context machine/installation identity is missing.";$dt=[DateTimeOffset]::MinValue;Require([DateTimeOffset]::TryParse([string]$Evidence.collectedAtUtc,[ref]$dt) -and $dt -ne [DateTimeOffset]::MinValue) "$Context timestamp is invalid.";ExactProps $Evidence.build @('commitSha','desktopExecutableSha256','manifestSha256','packageFingerprintSha256') "$Context build";Require([string]$Evidence.build.commitSha -ceq $ReleaseCommit) "$Context build commit does not equal the release commit.";foreach($h in @([string]$Evidence.build.desktopExecutableSha256,[string]$Evidence.build.manifestSha256,[string]$Evidence.build.packageFingerprintSha256)){Require($h -match '^[0-9a-f]{64}$') "$Context build hash is malformed."};ExactProps $Evidence.world @('environmentParentRevisionId','environmentRevisionId','environmentRevisionSha256','gameAdapterId','gameVersion','name','payloadByteSize','payloadSha256','sharingMode','statePackageId','stateParentRevisionId','stateRevisionId','stateRevisionSha256','worldId') "$Context world";Require([int64]$Evidence.world.payloadByteSize -gt 0 -and [string]$Evidence.world.payloadSha256 -match '^[0-9a-f]{64}$' -and [string]$Evidence.world.stateRevisionSha256 -match '^[0-9a-f]{64}$' -and [string]$Evidence.world.environmentRevisionSha256 -match '^[0-9a-f]{64}$') "$Context World fingerprint is malformed.";ValidateJournal $Evidence $Context;return $dt}
function CopyExact([string]$Source,[string]$Destination){$d=[IO.Path]::GetDirectoryName($Destination);[IO.Directory]::CreateDirectory($d)|Out-Null;[IO.File]::Copy($Source,$Destination,$false);Require((Get-FileHash -LiteralPath $Source -Algorithm SHA256).Hash -ceq (Get-FileHash -LiteralPath $Destination -Algorithm SHA256).Hash) "Copied evidence bytes changed: $Destination"}
function Ref([string]$Path,[string]$Hash){return [pscustomobject][ordered]@{path=$Path;sha256=$Hash}}

$sourceRoot=[IO.Path]::GetFullPath($BundleDirectory);Require([IO.Directory]::Exists($sourceRoot)) 'Deferred candidate directory is missing.';$rootItem=Get-Item -LiteralPath $sourceRoot;Require($null -eq $rootItem.LinkType) 'Deferred candidate directory cannot be a symbolic link.'
$manifestPath=Join-Path $sourceRoot 'release-manifest.json';$verifierPath=Join-Path $sourceRoot 'verify-closed-alpha-release.ps1';$selfPath=[IO.Path]::GetFullPath($PSCommandPath);Require([IO.File]::Exists($manifestPath) -and [IO.File]::Exists($verifierPath)) 'Deferred candidate is missing manifest/verifier.'
& $verifierPath -BundleDirectory $sourceRoot
$manifestText=[IO.File]::ReadAllText($manifestPath);$manifest=$manifestText|ConvertFrom-Json;Require([string]$manifest.documentType -ceq 'steward.closed-alpha-release-candidate' -and [int]$manifest.schemaVersion -eq 1 -and [string]$manifest.channel -ceq 'closed-alpha') 'Deferred candidate manifest identity is invalid.';Require(-not [bool]$manifest.publishAuthorization.publishAllowed -and [string]$manifest.publishAuthorization.physicalBringHere -ceq 'deferred' -and $null -eq $manifest.publishAuthorization.evidencePath -and $null -eq $manifest.publishAuthorization.evidenceSha256) 'Publication promotion requires an exact deferred candidate.'
$version=[string]$manifest.version;$commit=[string]$manifest.commitSha;Require($commit -match '^[0-9a-f]{40}$') 'Release commit is malformed.';$selfArtifacts=@($manifest.artifacts|Where-Object{[string]$_.path -ceq 'promote-closed-alpha-publication.ps1'});Require($selfArtifacts.Count -eq 1) 'Promotion tool must be manifest-bound exactly once.';$selfItem=Get-Item -LiteralPath $selfPath;Require($null -eq $selfItem.LinkType -and $selfItem.Length -eq [int64]$selfArtifacts[0].byteSize -and (Get-FileHash -LiteralPath $selfPath -Algorithm SHA256).Hash -ceq [string]$selfArtifacts[0].sha256) 'Promotion tool bytes do not match the candidate manifest.'
$sourceManifestHash=(Get-FileHash -LiteralPath $manifestPath -Algorithm SHA256).Hash.ToUpperInvariant()

$sb=ReadJson $SourceBeforeEvidencePath 2MB 'Physical source-before evidence';$ta=ReadJson $TargetAfterEvidencePath 2MB 'Physical target-after evidence';$sa=ReadJson $SourceAfterEvidencePath 2MB 'Physical source-after evidence'
$t1=ValidatePhysical $sb.Json 'source-before' $commit 'Physical source-before evidence';$t2=ValidatePhysical $ta.Json 'target-after' $commit 'Physical target-after evidence';$t3=ValidatePhysical $sa.Json 'source-after' $commit 'Physical source-after evidence';Require($t1 -le $t2 -and $t2 -le $t3) 'Physical checkpoint timestamps are not monotonic.'
Require((Canonical $sb.Json.build) -ceq (Canonical $ta.Json.build) -and (Canonical $sb.Json.build) -ceq (Canonical $sa.Json.build)) 'Physical checkpoints did not use the exact same byte-verified build.';Require((Canonical $sb.Json.world) -ceq (Canonical $ta.Json.world) -and (Canonical $sb.Json.world) -ceq (Canonical $sa.Json.world)) 'Physical World/revision/package evidence is not identical across checkpoints.';Require([string]$sb.Json.installationId -ceq [string]$sa.Json.installationId -and [string]$sb.Json.machineName -ieq [string]$sa.Json.machineName) 'Source-after is not from the original source machine/installation.';Require([string]$sb.Json.installationId -cne [string]$ta.Json.installationId -and [string]$sb.Json.machineName -ine [string]$ta.Json.machineName) 'Physical source and target are not distinct machines/installations.'
Require($null -eq $sb.Json.sourceEvidenceSha256 -and $null -eq $sb.Json.targetEvidenceSha256) 'Source-before evidence must not link earlier evidence.';Require([string]$ta.Json.sourceEvidenceSha256 -ieq $sb.Hash -and $null -eq $ta.Json.targetEvidenceSha256) 'Target-after does not bind the exact source-before JSON.';Require([string]$sa.Json.sourceEvidenceSha256 -ieq $sb.Hash -and [string]$sa.Json.targetEvidenceSha256 -ieq $ta.Hash) 'Source-after does not bind the exact source-before and target-after JSON.'

$shotSB=RequirePng $SourceBeforeScreenshotPath 'PC A source-before screenshot';$shotAvail=RequirePng $TargetAvailableScreenshotPath 'PC B Available/Bring-here screenshot';$shotTA=RequirePng $TargetAfterScreenshotPath 'PC B target-after screenshot';$shotSA=RequirePng $SourceAfterScreenshotPath 'PC A source-after screenshot'

$live=ReadJson $LiveHostExecutionChainPath 1MB 'Live-host execution chain';ExactProps $live.Json @('allStagesSucceeded','automaticCrossStageRollback','completedAtUtc','deploymentHandoffSha256','deploymentStagesUsedSsh','documentType','externalAcceptanceHostMutation','externalAcceptanceUsedSsh','externalObserverSeparation','physicalBringHere','publicationAuthorizationChanged','publishAllowed','releaseCommitSha','releaseVersion','requestSha256','schemaVersion','stageCount','stageEvidence') 'Live-host execution chain';Require([string]$live.Json.documentType -ceq 'steward.closed-alpha-live-host-execution-chain' -and [int]$live.Json.schemaVersion -eq 1) 'Live-host execution chain identity is invalid.';Require([string]$live.Json.releaseVersion -ceq $version -and [string]$live.Json.releaseCommitSha -ceq $commit) 'Live-host execution chain does not bind this release.';Require([int]$live.Json.stageCount -eq 5 -and [bool]$live.Json.allStagesSucceeded -and [bool]$live.Json.deploymentStagesUsedSsh -and -not [bool]$live.Json.externalAcceptanceUsedSsh -and -not [bool]$live.Json.externalAcceptanceHostMutation) 'Live-host execution chain does not prove the qualified deployment/external boundary.';Require([string]$live.Json.externalObserverSeparation -ceq 'operator-required-not-machine-attested' -and -not [bool]$live.Json.automaticCrossStageRollback) 'Live-host execution chain overstates observer/rollback guarantees.';Require(-not [bool]$live.Json.publishAllowed -and [string]$live.Json.physicalBringHere -ceq 'deferred' -and -not [bool]$live.Json.publicationAuthorizationChanged) 'Live-host execution chain was not produced from a deferred candidate.';Require([string]$live.Json.requestSha256 -match '^[0-9A-F]{64}$' -and [string]$live.Json.deploymentHandoffSha256 -match '^[0-9A-F]{64}$') 'Live-host execution chain binding hash is malformed.';$stages=@($live.Json.stageEvidence);Require($stages.Count -eq 5) 'Live-host execution chain does not contain five stage bindings.';$expectedTypes=@('steward.closed-alpha-live-host-preflight','steward.closed-alpha-live-plan-staging','steward.closed-alpha-live-backend-deployment','steward.closed-alpha-live-ingress-activation','steward.closed-alpha-external-ingress-acceptance');for($n=0;$n -lt 5;$n++){ExactProps $stages[$n] @('byteSize','documentType','file','sha256') "Live-host stage $n";Require([string]$stages[$n].documentType -ceq $expectedTypes[$n] -and [int64]$stages[$n].byteSize -gt 0 -and [string]$stages[$n].sha256 -match '^[0-9A-F]{64}$') "Live-host stage $n binding is invalid."}

$out=[IO.Path]::GetFullPath($OutputDirectory);Require(-not [IO.Directory]::Exists($out) -and -not [IO.File]::Exists($out)) 'Publication output path must not already exist.';$sourcePrefix=$sourceRoot.TrimEnd([IO.Path]::DirectorySeparatorChar,[IO.Path]::AltDirectorySeparatorChar)+[IO.Path]::DirectorySeparatorChar;Require(-not $out.StartsWith($sourcePrefix,[StringComparison]::OrdinalIgnoreCase) -and -not $sourceRoot.StartsWith($out.TrimEnd([IO.Path]::DirectorySeparatorChar,[IO.Path]::AltDirectorySeparatorChar)+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)) 'Publication output must be separate from the deferred candidate.';[IO.Directory]::CreateDirectory($out)|Out-Null
try{
    foreach($entry in @(Get-ChildItem -LiteralPath $sourceRoot -Force)){Copy-Item -LiteralPath $entry.FullName -Destination $out -Recurse -Force}
    $eRoot=Join-Path $out 'publication-evidence';[IO.Directory]::CreateDirectory($eRoot)|Out-Null
    $sourceManifestRel='publication-evidence/source-release-manifest.json';CopyExact $manifestPath (Join-Path $out $sourceManifestRel)
    $sbRel='publication-evidence/physical/source-before.json';$taRel='publication-evidence/physical/target-after.json';$saRel='publication-evidence/physical/source-after.json';CopyExact $sb.Path (Join-Path $out $sbRel);CopyExact $ta.Path (Join-Path $out $taRel);CopyExact $sa.Path (Join-Path $out $saRel)
    $shotSBRel='publication-evidence/physical/screenshots/source-before.png';$shotAvailRel='publication-evidence/physical/screenshots/target-available.png';$shotTARel='publication-evidence/physical/screenshots/target-after.png';$shotSARel='publication-evidence/physical/screenshots/source-after.png';CopyExact $shotSB.Path (Join-Path $out $shotSBRel);CopyExact $shotAvail.Path (Join-Path $out $shotAvailRel);CopyExact $shotTA.Path (Join-Path $out $shotTARel);CopyExact $shotSA.Path (Join-Path $out $shotSARel)
    $liveRel='publication-evidence/live-host-execution-chain.json';CopyExact $live.Path (Join-Path $out $liveRel)
    $physicalRel='publication-evidence/physical-pass.json';$physical=[pscustomobject][ordered]@{documentType='steward.bring-here-physical-pass';schemaVersion=1;completedAtUtc=$t3.ToUniversalTime().ToString('O');qualifiedKitCommitSha=$commit;sourceBefore=(Ref $sbRel $sb.Hash);targetAfter=(Ref $taRel $ta.Hash);sourceAfter=(Ref $saRel $sa.Hash);screenshots=[pscustomobject][ordered]@{sourceBefore=(Ref $shotSBRel $shotSB.Hash);targetAvailable=(Ref $shotAvailRel $shotAvail.Hash);targetAfter=(Ref $shotTARel $shotTA.Hash);sourceAfter=(Ref $shotSARel $shotSA.Hash)};uiObservationAttestation='operator-required-not-machine-attested'};$physicalJson=$physical|ConvertTo-Json -Depth 8;ExactProps ($physicalJson|ConvertFrom-Json) @('completedAtUtc','documentType','qualifiedKitCommitSha','schemaVersion','screenshots','sourceAfter','sourceBefore','targetAfter','uiObservationAttestation') 'Generated physical evidence summary';$physicalPath=Join-Path $out $physicalRel;[IO.File]::WriteAllText($physicalPath,$physicalJson,[Text.UTF8Encoding]::new($false));$physicalHash=(Get-FileHash -LiteralPath $physicalPath -Algorithm SHA256).Hash.ToUpperInvariant()
    $authRel='publication-evidence/publication-authorization.json';$auth=[pscustomobject][ordered]@{documentType='steward.closed-alpha-publication-authorization';schemaVersion=1;completedAtUtc=[DateTimeOffset]::UtcNow.ToString('O');releaseVersion=$version;releaseCommitSha=$commit;sourceDeferredManifest=(Ref $sourceManifestRel $sourceManifestHash);physicalPass=(Ref $physicalRel $physicalHash);liveHostExecution=(Ref $liveRel $live.Hash);physicalBringHerePassed=$true;liveHostAcceptancePassed=$true;physicalUiObservationAttestation='operator-required-not-machine-attested';externalObserverSeparation='operator-required-not-machine-attested';publishAllowed=$true};$authJson=$auth|ConvertTo-Json -Depth 8;ExactProps ($authJson|ConvertFrom-Json) @('completedAtUtc','documentType','externalObserverSeparation','liveHostAcceptancePassed','liveHostExecution','physicalBringHerePassed','physicalPass','physicalUiObservationAttestation','publishAllowed','releaseCommitSha','releaseVersion','schemaVersion','sourceDeferredManifest') 'Generated combined publication authorization';$authPath=Join-Path $out $authRel;[IO.File]::WriteAllText($authPath,$authJson,[Text.UTF8Encoding]::new($false));$authHash=(Get-FileHash -LiteralPath $authPath -Algorithm SHA256).Hash.ToUpperInvariant()
    $status=@"
SAFE WORLD CLOSED-ALPHA RELEASE STATUS
======================================

Version: $version
Commit: $commit

Publication authorization: ALLOWED
Physical Bring Here: PASSED (three exact probe checkpoints + four required screenshot files are hash-bound)
Live-host acceptance: PASSED (exact five-stage execution-chain evidence is hash-bound)

IMPORTANT LIMITS
----------------
Screenshot content and credential-free observer-machine separation remain operator-observed requirements; they are not machine-attested by this promotion tool. The bound evidence files preserve exactly what was reviewed.

This promoted candidate is authorized only because BOTH physical Bring Here and live-host acceptance evidence are present and validated by the strict release verifier.
"@;[IO.File]::WriteAllText((Join-Path $out 'RELEASE-STATUS.txt'),$status.Replace("`r`n","`n"),[Text.UTF8Encoding]::new($false))
    $promotedManifest=$manifestText|ConvertFrom-Json;$promotedManifest.publishAuthorization.physicalBringHere='passed';$promotedManifest.publishAuthorization.publishAllowed=$true;$promotedManifest.publishAuthorization.reason='Authorized only after exact physical Bring Here evidence and exact live-host execution acceptance are jointly bound.';$promotedManifest.publishAuthorization.evidencePath=$authRel;$promotedManifest.publishAuthorization.evidenceSha256=$authHash
    $promotedArtifacts=@(Get-ChildItem -LiteralPath $out -Recurse -File|Where-Object{[IO.Path]::GetFullPath($_.FullName) -ne [IO.Path]::GetFullPath((Join-Path $out 'release-manifest.json'))}|Sort-Object FullName|ForEach-Object{Require($null -eq $_.LinkType) "Promoted artifact cannot be a symbolic link: $($_.FullName)";[ordered]@{path=[IO.Path]::GetRelativePath($out,$_.FullName).Replace('\','/');byteSize=$_.Length;sha256=(Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash.ToUpperInvariant()}});$promotedManifest.artifacts=$promotedArtifacts;[IO.File]::WriteAllText((Join-Path $out 'release-manifest.json'),($promotedManifest|ConvertTo-Json -Depth 10),[Text.UTF8Encoding]::new($false))
    & (Join-Path $out 'verify-closed-alpha-release.ps1') -BundleDirectory $out -RequirePublishAuthorized
    Write-Host;Write-Host '[OK] Closed-alpha publication candidate is jointly authorized.';Write-Host "  Version: $version";Write-Host "  Commit: $commit";Write-Host "  Deferred source manifest SHA-256: $sourceManifestHash";Write-Host "  Physical pass SHA-256: $physicalHash";Write-Host "  Live-host execution chain SHA-256: $($live.Hash)";Write-Host "  Combined authorization SHA-256: $authHash";Write-Host '  Physical screenshot content: operator-reviewed, hash-bound, not machine-interpreted';Write-Host '  External observer credential separation: operator-required, not machine-attested';Write-Host '  Publish authorization: ALLOWED'
}
catch{if([IO.Directory]::Exists($out)){Remove-Item -LiteralPath $out -Recurse -Force -ErrorAction SilentlyContinue};throw}
