[CmdletBinding()]
param()
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
function Require([bool]$Condition,[string]$Message){if(-not $Condition){throw $Message}}
function WriteUtf8([string]$Path,[string]$Text){$d=[IO.Path]::GetDirectoryName([IO.Path]::GetFullPath($Path));[IO.Directory]::CreateDirectory($d)|Out-Null;[IO.File]::WriteAllText($Path,$Text.Replace("`r`n","`n"),[Text.UTF8Encoding]::new($false))}
function ExpectFail([scriptblock]$Action,[string]$Context,[string]$Expected){$failed=$false;try{& $Action}catch{$failed=$true;$m=[string]$_.Exception.Message;Require($m.Contains($Expected,[StringComparison]::Ordinal)) "${Context} failed for the wrong reason: $m";Write-Host "[EXPECTED] ${Context}: $m"};Require $failed "Expected failure did not occur: $Context"}
function HashLower([string]$Text){$bytes=[Text.Encoding]::UTF8.GetBytes($Text);return [Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($bytes)).ToLowerInvariant()}
function WritePng([string]$Path,[byte]$Marker){$d=[IO.Path]::GetDirectoryName([IO.Path]::GetFullPath($Path));[IO.Directory]::CreateDirectory($d)|Out-Null;$b=[byte[]]::new(512);$sig=[byte[]](0x89,0x50,0x4E,0x47,0x0D,0x0A,0x1A,0x0A);[Array]::Copy($sig,$b,8);for($n=8;$n -lt $b.Length;$n++){$b[$n]=[byte](($Marker+$n)%251)};[IO.File]::WriteAllBytes($Path,$b)}
function Evidence([string]$Role,[string]$Commit,[string]$Machine,[string]$Install,[string]$SourceHash,[string]$TargetHash){$build=[ordered]@{commitSha=$Commit;manifestSha256=('1'*64);packageFingerprintSha256=('2'*64);desktopExecutableSha256=('3'*64)};$world=[ordered]@{worldId='11111111-1111-1111-1111-111111111111';name='Synthetic World';gameAdapterId='synthetic';sharingMode=0;stateRevisionId='22222222-2222-2222-2222-222222222222';environmentRevisionId='33333333-3333-3333-3333-333333333333';stateParentRevisionId=$null;environmentParentRevisionId=$null;statePackageId='pkg-synthetic';gameVersion='1.0';stateRevisionSha256=('4'*64);environmentRevisionSha256=('5'*64);payloadByteSize=4096;payloadSha256=('6'*64)};$journal=[ordered]@{installationId=$Install;desiredStateRevisionId=$world.stateRevisionId;desiredEnvironmentRevisionId=$world.environmentRevisionId;confirmedStateRevisionId=$world.stateRevisionId;confirmedEnvironmentRevisionId=$world.environmentRevisionId;desiredName=$world.name;desiredGameAdapterId=$world.gameAdapterId;confirmedName=$world.name;confirmedGameAdapterId=$world.gameAdapterId;isSynchronized=$true};return [ordered]@{documentType='safe-world.bring-here-two-pc-evidence';schemaVersion=1;role=$Role;collectedAtUtc=[DateTimeOffset]::UtcNow.ToString('O');machineName=$Machine;desktopProcessCount=1;installationId=$Install;build=$build;world=$world;journal=$journal;sourceEvidenceSha256=if([string]::IsNullOrEmpty($SourceHash)){$null}else{$SourceHash};targetEvidenceSha256=if([string]::IsNullOrEmpty($TargetHash)){$null}else{$TargetHash}}}
function WriteManifest([string]$Bundle,[string]$Version,[string]$Commit){$arts=@(Get-ChildItem -LiteralPath $Bundle -Recurse -File|Where-Object{[IO.Path]::GetFileName($_.FullName) -cne 'release-manifest.json'}|Sort-Object FullName|ForEach-Object{[ordered]@{path=[IO.Path]::GetRelativePath($Bundle,$_.FullName).Replace('\','/');byteSize=$_.Length;sha256=(Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash.ToUpperInvariant()}});$m=[ordered]@{documentType='steward.closed-alpha-release-candidate';schemaVersion=1;channel='closed-alpha';version=$Version;commitSha=$Commit;builtAtUtc=[DateTimeOffset]::UtcNow.AddMinutes(-5).ToString('O');deployment=[ordered]@{apiBaseUrl='https://alpha-publication.example.com/';authenticationMode='friends-build';backendImageId=('sha256:'+('a'*64));backendImageTag='steward-backend:publication-test';backendRuntimeUser='app';objectStorageProtocol='s3-compatible';postgresMajorVersion=17;targetPlatform='linux/amd64'};publishAuthorization=[ordered]@{physicalBringHere='deferred';publishAllowed=$false;reason='Synthetic publication qualification remains deferred until evidence is supplied.';evidencePath=$null;evidenceSha256=$null};artifacts=$arts};WriteUtf8 (Join-Path $Bundle 'release-manifest.json') ($m|ConvertTo-Json -Depth 8)}
function MakeInputs([string]$Root,[string]$Commit){$p=Join-Path $Root 'inputs';[IO.Directory]::CreateDirectory($p)|Out-Null;$sb=Evidence 'source-before' $Commit 'PC-A' 'install-a' '' '';$sbPath=Join-Path $p 'source-before.json';WriteUtf8 $sbPath ($sb|ConvertTo-Json -Depth 8);$sbHash=(Get-FileHash $sbPath -Algorithm SHA256).Hash.ToLowerInvariant();Start-Sleep -Milliseconds 5;$ta=Evidence 'target-after' $Commit 'PC-B' 'install-b' $sbHash '';$taPath=Join-Path $p 'target-after.json';WriteUtf8 $taPath ($ta|ConvertTo-Json -Depth 8);$taHash=(Get-FileHash $taPath -Algorithm SHA256).Hash.ToLowerInvariant();Start-Sleep -Milliseconds 5;$sa=Evidence 'source-after' $Commit 'PC-A' 'install-a' $sbHash $taHash;$saPath=Join-Path $p 'source-after.json';WriteUtf8 $saPath ($sa|ConvertTo-Json -Depth 8);$s1=Join-Path $p 'source-before.png';$s2=Join-Path $p 'target-available.png';$s3=Join-Path $p 'target-after.png';$s4=Join-Path $p 'source-after.png';WritePng $s1 11;WritePng $s2 22;WritePng $s3 33;WritePng $s4 44;$chain=[ordered]@{documentType='steward.closed-alpha-live-host-execution-chain';schemaVersion=1;completedAtUtc=[DateTimeOffset]::UtcNow.ToString('O');releaseVersion='2.0.0-publication-test';releaseCommitSha=$Commit;requestSha256=('A'*64);deploymentHandoffSha256=('B'*64);stageEvidence=@([ordered]@{file='01.json';documentType='steward.closed-alpha-live-host-preflight';byteSize=100;sha256=('C'*64)},[ordered]@{file='02.json';documentType='steward.closed-alpha-live-plan-staging';byteSize=100;sha256=('D'*64)},[ordered]@{file='03.json';documentType='steward.closed-alpha-live-backend-deployment';byteSize=100;sha256=('E'*64)},[ordered]@{file='04.json';documentType='steward.closed-alpha-live-ingress-activation';byteSize=100;sha256=('F'*64)},[ordered]@{file='05.json';documentType='steward.closed-alpha-external-ingress-acceptance';byteSize=100;sha256=('1'*64)});stageCount=5;allStagesSucceeded=$true;deploymentStagesUsedSsh=$true;externalAcceptanceUsedSsh=$false;externalAcceptanceHostMutation=$false;externalObserverSeparation='operator-required-not-machine-attested';automaticCrossStageRollback=$false;publishAllowed=$false;physicalBringHere='deferred';publicationAuthorizationChanged=$false};$chainPath=Join-Path $p 'live-chain.json';WriteUtf8 $chainPath ($chain|ConvertTo-Json -Depth 8);return [ordered]@{SourceBefore=$sbPath;TargetAfter=$taPath;SourceAfter=$saPath;SourceBeforeShot=$s1;TargetAvailableShot=$s2;TargetAfterShot=$s3;SourceAfterShot=$s4;Chain=$chainPath}}
function Promote([string]$Bundle,[object]$I,[string]$Output){& (Join-Path $Bundle 'promote-closed-alpha-publication.ps1') -BundleDirectory $Bundle -SourceBeforeEvidencePath $I.SourceBefore -TargetAfterEvidencePath $I.TargetAfter -SourceAfterEvidencePath $I.SourceAfter -SourceBeforeScreenshotPath $I.SourceBeforeShot -TargetAvailableScreenshotPath $I.TargetAvailableShot -TargetAfterScreenshotPath $I.TargetAfterShot -SourceAfterScreenshotPath $I.SourceAfterShot -LiveHostExecutionChainPath $I.Chain -OutputDirectory $Output}

$work=Join-Path ([IO.Path]::GetTempPath()) ('steward-publication-test-'+[Guid]::NewGuid().ToString('N'));$bundle=Join-Path $work 'bundle';$version='2.0.0-publication-test';$commit='8'*40
try{
[IO.Directory]::CreateDirectory((Join-Path $bundle 'desktop'))|Out-Null;[IO.Directory]::CreateDirectory((Join-Path $bundle 'backend'))|Out-Null;Copy-Item (Join-Path $PSScriptRoot 'verify-closed-alpha-release.ps1') (Join-Path $bundle 'verify-closed-alpha-release.ps1');Copy-Item (Join-Path $PSScriptRoot 'promote-closed-alpha-publication.ps1') (Join-Path $bundle 'promote-closed-alpha-publication.ps1');WriteUtf8 (Join-Path $bundle 'desktop/Steward.zip') 'synthetic desktop archive bytes';WriteUtf8 (Join-Path $bundle 'backend/steward-backend.tar') 'synthetic backend image tar bytes';WriteUtf8 (Join-Path $bundle 'backend/deployment.env.example') 'PORT=8080';WriteUtf8 (Join-Path $bundle 'CLOSED-ALPHA-OPERATOR-RUNBOOK.txt') 'synthetic runbook';WriteUtf8 (Join-Path $bundle 'RELEASE-STATUS.txt') 'DEFERRED';WriteManifest $bundle $version $commit;& (Join-Path $bundle 'verify-closed-alpha-release.ps1') -BundleDirectory $bundle;ExpectFail {& (Join-Path $bundle 'verify-closed-alpha-release.ps1') -BundleDirectory $bundle -RequirePublishAuthorized} 'deferred candidate remains blocked' 'publishing is blocked'
$I=MakeInputs $work $commit;$promoted=Join-Path $work 'promoted';Promote $bundle $I $promoted;& (Join-Path $promoted 'verify-closed-alpha-release.ps1') -BundleDirectory $promoted -RequirePublishAuthorized;$pm=[IO.File]::ReadAllText((Join-Path $promoted 'release-manifest.json'))|ConvertFrom-Json;Require([bool]$pm.publishAuthorization.publishAllowed -and [string]$pm.publishAuthorization.physicalBringHere -ceq 'passed') 'Positive promotion did not authorize publication.';Require([string]$pm.publishAuthorization.evidencePath -ceq 'publication-evidence/publication-authorization.json') 'Positive promotion did not bind the combined authorization summary.'
$badCommitRoot=Join-Path $work 'bad-commit';Copy-Item $I.SourceBefore (Join-Path $work 'bad-source.json');$bad=[IO.File]::ReadAllText((Join-Path $work 'bad-source.json'))|ConvertFrom-Json;$bad.build.commitSha='9'*40;WriteUtf8 (Join-Path $work 'bad-source.json') ($bad|ConvertTo-Json -Depth 8);$badI=$I.Clone();$badI.SourceBefore=Join-Path $work 'bad-source.json';ExpectFail {Promote $bundle $badI $badCommitRoot} 'physical build commit mismatch is rejected' 'build commit does not equal the release commit'
$brokenPath=Join-Path $work 'broken-source-after.json';$broken=[IO.File]::ReadAllText($I.SourceAfter)|ConvertFrom-Json;$broken.targetEvidenceSha256='0'*64;WriteUtf8 $brokenPath ($broken|ConvertTo-Json -Depth 8);$brokenI=$I.Clone();$brokenI.SourceAfter=$brokenPath;ExpectFail {Promote $bundle $brokenI (Join-Path $work 'broken-link')} 'broken physical evidence link is rejected' 'does not bind the exact source-before and target-after JSON'
$badPng=Join-Path $work 'not-a-png.png';WriteUtf8 $badPng ('x'*512);$pngI=$I.Clone();$pngI.TargetAvailableShot=$badPng;ExpectFail {Promote $bundle $pngI (Join-Path $work 'bad-png')} 'invalid screenshot evidence is rejected' 'is not a PNG screenshot'
$badChainPath=Join-Path $work 'bad-chain.json';$bc=[IO.File]::ReadAllText($I.Chain)|ConvertFrom-Json;$bc.externalAcceptanceUsedSsh=$true;WriteUtf8 $badChainPath ($bc|ConvertTo-Json -Depth 8);$chainI=$I.Clone();$chainI.Chain=$badChainPath;ExpectFail {Promote $bundle $chainI (Join-Path $work 'bad-chain-output')} 'SSH-using external acceptance is rejected' 'does not prove the qualified deployment/external boundary'
$runtime=Join-Path $promoted 'backend/deployment.env.example';Add-Content -LiteralPath $runtime -Value 'TAMPER=1';$tamperedManifest=[IO.File]::ReadAllText((Join-Path $promoted 'release-manifest.json'))|ConvertFrom-Json;$entry=@($tamperedManifest.artifacts|Where-Object{[string]$_.path -ceq 'backend/deployment.env.example'})[0];$ri=Get-Item $runtime;$entry.byteSize=$ri.Length;$entry.sha256=(Get-FileHash $runtime -Algorithm SHA256).Hash.ToUpperInvariant();WriteUtf8 (Join-Path $promoted 'release-manifest.json') ($tamperedManifest|ConvertTo-Json -Depth 10);ExpectFail {& (Join-Path $promoted 'verify-closed-alpha-release.ps1') -BundleDirectory $promoted -RequirePublishAuthorized} 'runtime rewrite remains rejected even with rewritten manifest hash' 'Publication promotion changed original artifact'
Write-Host '[OK] Conjunctive physical + live-host publication authorization and adversarial refusals passed.'
}finally{if([IO.Directory]::Exists($work)){Remove-Item $work -Recurse -Force -ErrorAction SilentlyContinue}}
